server:
  port: 8080

spring:
  graphql:
    path: /api/v1/demo2/graphql
  application:
    name: demo-graphql-service

#eureka:
#  instance:
#    appname: demo-graphql-service
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true